### ISSUE TITLE
Support For Raw SQL Queries

### ISSUE THREAD

**Issue by AdrianMcGrathRiptide** [boylesoftware/x2node-dbos#1]
We need support for Raw SQL Queries, so we can do things such as provisioning the tables based on the models. Perhaps something like a RawDBO class.

**Comment by levahim** [comment]
The idea is that you don't need a generic DBO object if you build the SQL yourself for a given operation. Instead, you can get the underlying database connection either from the transaction object (see https://boylesoftware.github.io/x2node-api-reference/module-x2node-dbos-Transaction.html#connection__anchor) or from the datasource provided by the DBO factory (see https://boylesoftware.github.io/x2node-api-reference/module-x2node-dbos-DBOFactory.html#adaptDataSource__anchor). Once you have the connection, you can run raw SQL queries on it. If your query returns a result set, you can parse it with the low level x2node-rsparser module. The main purpose of the four generic DBOs is to automatically construct and run SQL. Let me know if this addresses what you're asking.

**Comment by levahim** [comment]
Closing on assumption that the question is answered.
