### ISSUE TITLE
Group By Queries

### ISSUE THREAD

**Issue by AdrianMcGrathRiptide** [boylesoftware/x2node-dbos#10]
Are there any recommendations for doing some group by queries? I know the raw queries is always an option, but I'm wondering if there's some built-in way of doing it that I'm missing. 
For example, if we had the following objects: 
```
Company: id
User: id, company, last_login
```

And let's say we wanted to get the number of users by company and the month of their last login date over the last 12 months. The equivalent SQL query would probably be something similar to:

`SELECT company, YEAR(last_login), MONTH(last_login), COUNT(*) FROM `users` WHERE last_login BETWEEN '2017-11-10 00:00:00' AND '2018-11-10 00:00:00' ORDER BY company, YEAR(last_login), MONTH(last_login)`

**Comment by levahim** [comment]
You can define aggregate map properties on your record types (see last paragraph of https://github.com/boylesoftware/x2node-dbos#aggregate-properties) and it will be handled automatically by the framework, but it will only aggregate by a single key property. In your case, when you want to aggregate by more than one property, it becomes a bit more complicated (e.g. how do you represent the result in JSON used for the records). So, in your case it's either you come up with an alternative data structure where your aggregation keys can be represented as a single property on the record, or--custom queries, as you mentioned.

Now, one solution that _may_ work for you is to aggregate by the last login date but fetch by company. So, for example, you could have your record type definitions:

```javascript
'User': {
  properties: {
    'id': {
      valueType: 'number',
      role: 'id'
    },
    'companyRef': {
      valueType: 'ref(Company)'
    },
    'lastLoginDate': {
      valueType: 'string' // for example, as 'yyyy-mm-dd'
    },
    ...
  }
},
'Company': {
  properties: {
    'id': {
      valueType: 'number',
      role: 'id'
    },
    ...
    'userRefs': {
      valueType: 'ref(User)[]',
      reverseRefProperty: 'companyRef'
    },
    'countLoginsByDateRange': {
      valueType: 'number{}',
      keyPropertyName: 'lastLoginDate',
      aggregate: {
        collection: 'userRefs',
        valueExpr: 'id => count',
        filter: [
          [ 'lastLoginDate => ge', dbos.param('lastLoginDateFrom') ],
          [ 'lastLoginDate => lt', dbos.param('lastLoginDateTo') ]
        ]
      }
    }
  }
}
```
Then you can query it like:

```javascript
dboFactory.buildFetch('Company', {
  props: [ 'id', 'countLoginsByDateRange' ]
}).execute(connection, null, {
  lastLoginDateFrom: '2017-11-10',
  lastLoginDateTo: '2018-11-10'
}).then(result => {
  // process the result
});
```

In the result you're going to have a list of company records and each record will have `countLoginsByDateRange` property as a map with keys being the dates in `yyyy-mm-dd` format and values being the counts of that company users with the corresponding last login dates.
