### ISSUE TITLE
Support For In Memory Database

### ISSUE THREAD

**Issue by AdrianMcGrathRiptide** [boylesoftware/x2node-dbos#2]
We need support for an in memory database for integration testing. We don't really mind what in memory database is supported.

**Comment by levahim** [comment]
The DBOs module currently supports only MySQL (and compatibles) and PostgreSQL. In general, I'd say that it's best to test your app against the same database type that's going to be actually used. Having said that, MySQL has a Memory storage engine. We never tested the DBOs module against it, but you can definitely try (would love the feedback!). We also plan to implement support for SQLite next.

**Comment by AdrianMcGrathRiptide** [comment]
Do you guys have an ETA on the SQLite driver, or has work been started on it?

**Comment by levahim** [comment]
The work on it has not started yet. But we plan to have it by September.

**Comment by levahim** [comment]
Closing for now. Stay tuned for the SQLite driver implementation.

**Comment by ajagnanan** [comment]
#3
