### ISSUE TITLE
Hardcoded SQL outside of Drivers

### ISSUE THREAD

**Issue by AdrianMcGrathRiptide** [boylesoftware/x2node-dbos#8]
We came across some hardcode SQL outside of the Drivers. Specifically, the following is causing us issues:
https://github.com/boylesoftware/x2node-dbos/blob/master/lib/filter-builder.js#L389

`SELECT TRUE FROM ...` is not valid syntax in SQLite. It should probably be updated to `SELECT 1 FROM ...` so that it plays nice with more databases, or it should be moved to the driver classes so the syntax can be defined by database.

**Comment by levahim** [comment]
Good point. Will be moved to the drivers.

**Comment by AdrianMcGrathRiptide** [comment]
Cool. Do you guys know when you think it will be completed?

**Comment by levahim** [comment]
Done. Replaced TRUE with 1 to improve SQL compatibility.
